{% set name = "bigearthnet-common" %}
{% set version = "2.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bigearthnet_common-{{ version }}.tar.gz
  sha256: ebfd9855378b0b8c7cfebf227508b4ef4900ed26ca6e6e77800e4c85aa7b8c68

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ben_constant_prompt = bigearthnet_common.constants:ben_constant_prompt

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - appdirs >=1.4,<2.0
    - fastcore >=1.3,<2.0
    - geopandas >=0.10,<0.11
    - natsort >=8,<9
    - pyarrow >=6,<7
    - pydantic >=1.8,<2.0
    - pygeos >=0.12,<0.13
    - python >=3.6,<4.0
    - rich >=10,<11
    - typer >=0.4,<0.5

test:
  imports:
    - bigearthnet_common
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kai-tub/bigearthnet_common
  summary: A collection of common tools to interact with the BigEarthNet dataset.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kai-tub
